### ISSUE TITLE
JwtAuthenticationMessageHandler Produces Null Log4Net Entries

### ISSUE THREAD

**Issue by adamfisher** [jamiekurtz/JwtAuthForWebAPI#11]
I am using [Swashbuckle](https://github.com/domaindrivendev/Swashbuckle) to render Swagger documentation for our web service and keep getting a bunch of null message entries generated at startup from the [JwtAuthenticationMessageHandler](https://github.com/jamiekurtz/JwtAuthForWebAPI/blob/master/src/JwtAuthForWebAPI/JwtAuthenticationMessageHandler.cs). I also see at least one generated on every request.. I know Swagger makes many callbacks to get other information and I suspect it has something to do with this since there would be no token/session at that time.

Is there a way to stop these entries from showing up? Maybe an example of a log4net filter for the appender to filter null entries from the appender?

```
DEBUG 2015-07-28 15:10:19,673 [8]  2726ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:19,781 [6]  2834ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:19,880 [6]  2933ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:19,886 [8]  2939ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:19,886 [7]  2939ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:19,893 [9]  2946ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:19,942 [6]  2995ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:19,994 [8]  3047ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:20,047 [10]  3100ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:20,047 [7]  3100ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:20,097 [9]  3150ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:20,143 [8]  3196ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:20,191 [10]  3244ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:20,239 [7]  3292ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:20,287 [8]  3340ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:20,383 [9]  3436ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:20,404 [10]  3457ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:20,697 [10]  3750ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:20,759 [9]  3812ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:20,968 [9]  4021ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:20,968 [6]  4021ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:20,971 [7]  4024ms JwtAuthForWebAPI - (null)
DEBUG 2015-07-28 15:10:20,981 [10]  4034ms JwtAuthForWebAPI - (null)
```

**Comment by adamfisher** [comment]
I also tried setting the logging level higher than debug but it still generates these messages.

**Comment by jamiekurtz** [comment]
That's very strange, indeed! I'll take a look, thanks for letting me know.

Can you give me your current log4net config section?

**Comment by adamfisher** [comment]
Mmmh. I think this might just be a configuration issue on my side. I was messing with the level value for the logger (set it to INFO) but I still want the appenders to log stuff at the debug level since I have other things that call log4net. Still curious what those other null entries mean since it looks like the message strings are all formatted with a prefix message in the handler.

``` xml
<log4net>
  <root>
    <level value="DEBUG" />
    <appender-ref ref="RollingFileAppender" />
    <appender-ref ref="DbAppender" />
  </root>
  <logger name="JwtAuthForWebAPI.JwtAuthenticationMessageHandler">
    <level value="INFO" />
  </logger>
  <appender name="RollingFileAppender" type="log4net.Appender.RollingFileAppender">
    <param name="File" value="..\Logs\MyLog.log" />
    <param name="AppendToFile" value="true" />
    <rollingStyle value="Composite" />
    <datePattern value="yyyMMdd" />
    <maximumFileSize value="50MB" />
    <maxSizeRollBackups value="10" />
    <staticLogFileName value="true" />
  </appender>
  <appender name="DbAppender" type="MyApp.Diagnostics.log4net.Appenders.DatabaseAppender"/>
</log4net>
```

**Comment by jamiekurtz** [comment]
Without debugging the code, it looks to me like you are missing the layout
section for the log4net appender. It should look something like this:

```
  <layout type="log4net.Layout.PatternLayout">
    <conversionPattern value="%date %-5level [%thread] %logger -
```

%message%newline%exception" />
      </layout>

The SampleSite project in the source tree includes a web.config with
log4net config:
https://github.com/jamiekurtz/JwtAuthForWebAPI/blob/master/src/JwtAuthForWebAPI.SampleSite/Web.config#L22

Give that a shot, and let me know if solves the problem.

**Comment by adamfisher** [comment]
Thanks Jamie. I did add a layout section but still outputs those null lines. For now I just set both the root logging level and the JWT logger to INFO and that gets rid of those lines. Good enough for now :-)  Thanks!
