### ISSUE TITLE
Expiration check during validation doesnt seem to work.

### ISSUE THREAD

**Issue by ronnieoverby** [jamiekurtz/JwtAuthForWebAPI#16]
JWT: `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJyb0Byb25uLmlvIiwiZW1haWwiOiJyb0Byb25uLmlvIiwicm9sZSI6IkFkbWluIiwiYXBwLnBlcm0iOlsiTWFuYWdlVXNlcnMiLCJFZGl0T3RoZXJVc2Vyc1RpbWUiXSwiaXNzIjoic2VsZiIsImF1ZCI6Imh0dHA6Ly93d3cuZXhhbXBsZS5jb20iLCJleHAiOjE0NjYwMTIyNzksIm5iZiI6MTQ2NjAxMjI2OX0.ccTeFosbKPglJelekTS47RXCPMDIltN8Q8EXTgYn4r8`

Decoded payload:

``` JSON
{
  "nameid": "1",
  "unique_name": "user@fake.com.com",
  "email": "user@fake.com.com",
  "role": "Admin",
  "app.perm": [
    "ManageUsers",
    "EditOtherUsersTime"
  ],
  "iss": "self",
  "aud": "http://www.example.com",
  "exp": 1466012279,
  "nbf": 1466012269
}
```

NBF, EXP converted to UTC times, respectively:
6/15/2016 5:37:49 PM
6/15/2016 5:37:59 PM

Epoch seconds to UTC conversion via:

``` C#
new DateTime(1970,1,1,0,0,0,0,DateTimeKind.Utc).AddSeconds(numberOfSeconds)
// not sure if this complies with what I saw in RFC about ignoring leap seconds
// somehow I think the CLR AddSeconds method does account for leap seconds
```

I created my JWT via

``` C#
        private string CreateJwt(DbUser user)
        {
            var securityKey = new SecurityTokenBuilder()
                .CreateFromKey(new AppSettings().JwtSecret) // byte[]
                .SecurityKeys.Single();

            var tokenHandler = new JwtSecurityTokenHandler();
            var now = DateTime.UtcNow;

            var claims = /* omitted */;

            var tokenDescriptor = new SecurityTokenDescriptor
            {
                Subject = new ClaimsIdentity(claims),
                TokenIssuerName = "self",

                AppliesToAddress = "http://www.example.com",
                Lifetime = new Lifetime(now, now.AddSeconds(10)), // small expiration for testing
                SigningCredentials = new SigningCredentials(
                    securityKey,
                    SecurityAlgorithms.HmacSha256Signature,
                    SecurityAlgorithms.Sha256Digest),
            };

            var token = tokenHandler.CreateToken(tokenDescriptor);

            var tokenString = tokenHandler.WriteToken(token);
            return tokenString;
        }
```

Anyway, when testing, the token seems to last much longer than 10 seconds when validating using your library.

Any thoughts?

Do you see anything wrong with what I'm doing?

**Comment by jamiekurtz** [comment]
Hey @ronnieoverby - try making the expiration date/time earlier than 10 minutes ago. Per the [JWT spec](https://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#rfc.section.4.1.4), implementers are allowed a small "grace" period to account for clock skew. And if I recall, the underlying .NET JwtSecurityTokenHandler has a default MaxClockSkew of 5 minutes... meaning you likely won't see a validation error for expired token if the `exp` value was more recent than 5 minutes. 

There's also a test in place for checking token expiration: https://github.com/jamiekurtz/JwtAuthForWebAPI/blob/master/src/JwtAuthForWebAPI.SampleClient/SmokeTests.cs#L97 .

Hope that helps, let me know if not.

**Comment by ronnieoverby** [comment]
Good to know. I've been tweaking the expiration times and the way it behaves seems to be consistent with how you describe it. Thanks!
