### ISSUE TITLE
creating the token to pass to the client 

### ISSUE THREAD

**Issue by Vaevictus** [jamiekurtz/JwtAuthForWebAPI#17]
Hi,

I think I'm missing something from the docs, and that is how to generate the token that will be sent to the client on a successful login. 

I have written an SPA that the user will need to log in via a restful api call. From what I've read about JWT, this authorisation controller should validate the supplied user/pass and generate a token. Is this something outside the scope of your library?

Thanks

**Comment by jamiekurtz** [comment]
Hi @Vaevictus - The library itself doesn't create JWTs, but I do have some test code in the SampleSite project that does so. Check this out:  https://github.com/jamiekurtz/JwtAuthForWebAPI/blob/master/src/JwtAuthForWebAPI.SampleClient/SmokeTests.cs#L218

The controller's authorization code should indeed validate the token. The link between token validation and token generation is the signature. You can use a shared key or a certificate, for example. In other words, the code that validates the token (in my library) needs the same shared key or certificate's public key that was used to create the token in the first place.

Hope that helps.

**Comment by Vaevictus** [comment]
thanks - that helps.
